/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Events
         * @description Newest first. IDs are UUIDv7, so the ID order is the order the events were written.
         */
        get: operations["audit_events_v1_admin_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_v1_admin_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kill-switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Switches */
        put: operations["switches_v1_admin_kill_switches_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ledger/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ledger Check
         * @description Walk the journal hash chain and check every run's clearing and hold accounts.
         */
        get: operations["ledger_check_v1_admin_ledger_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Network
         * @description The whole graph: gross invoice edges before netting, settlement transfers after.
         */
        get: operations["admin_network_v1_admin_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_v1_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Run */
        get: operations["admin_run_v1_admin_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort
         * @description Release every hold and return the run's invoices for the next window.
         */
        post: operations["abort_v1_admin_runs__run_id__abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/runs/{run_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle
         * @description Prepare and commit; repeating it resumes an interrupted settlement or does nothing.
         */
        post: operations["settle_v1_admin_runs__run_id__settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/windows/current/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_v1_admin_windows_current_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_v1_confirmations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/counterparties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counterparties */
        get: operations["counterparties_v1_counterparties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Currencies */
        get: operations["list_currencies_v1_currencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/expire-approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expire Approvals
         * @description Remove members who have not approved, then recompute (the approval deadline).
         */
        post: operations["expire_approvals_v1_demo_expire_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/funding-failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Funding Failure
         * @description Mark a payer as unable to fund (or able again); the next prepare excludes it.
         */
        post: operations["funding_failure_v1_demo_funding_failure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_v1_demo_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personas */
        get: operations["personas_v1_demo_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_v1_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/scenarios/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scenario */
        post: operations["scenario_v1_demo_scenarios__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/simulate-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_v1_demo_simulate_confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/estimates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate
         * @description Break-even calculation. Read-only, so no Idempotency-Key is needed.
         */
        post: operations["estimate_v1_estimates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoices */
        get: operations["list_invoices_v1_invoices_get"];
        put?: never;
        /** Create */
        post: operations["create_v1_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/template.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_v1_invoices_template_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_v1_invoices_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_v1_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoices/{invoice_id}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_v1_invoices__invoice_id__confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Member */
        get: operations["get_my_member_v1_members_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/network/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Network
         * @description Own counterparties and flows only; the settlement counterparty is Mesh settlement.
         */
        get: operations["my_network_v1_network_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_v1_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rates */
        get: operations["list_rates_v1_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Savings
         * @description Per-run and cumulative savings; totals count settled runs only.
         */
        get: operations["savings_v1_savings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statement */
        get: operations["statement_v1_statements__statement_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/statements/{statement_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_v1_statements__statement_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/windows/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_v1_windows_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBalance */
        AccountBalance: {
            /** Balance Minor */
            balance_minor: number;
            /** Currency */
            currency: string;
        };
        /** AdminOverview */
        AdminOverview: {
            /** Kill Switches */
            kill_switches: components["schemas"]["KillView"][];
            /** Members */
            members: components["schemas"]["MemberRow"][];
            /** Runs */
            runs: components["schemas"]["RunView"][];
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Content Hash */
            content_hash: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REJECT";
            /** Reason Code */
            reason_code?: string | null;
        };
        /** AuditView */
        AuditView: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** After Hash */
            after_hash: string | null;
            /** Before Hash */
            before_hash: string | null;
            /** Correlation Id */
            correlation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason Code */
            reason_code: string | null;
            /** Run Id */
            run_id: string | null;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Subject Type */
            subject_type: string;
        };
        /** BalanceOut */
        BalanceOut: {
            available: components["schemas"]["Money"];
            /** Currency */
            currency: string;
            held: components["schemas"]["Money"];
        };
        /** CaseView */
        CaseView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string | null;
            /** Run Id */
            run_id: string | null;
            /** Status */
            status: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Subject Name */
            subject_name: string | null;
            /** Subject Type */
            subject_type: string;
            /** Type */
            type: string;
        };
        /** ClearingBreak */
        ClearingBreak: {
            /** Account Type */
            account_type: string;
            /** Balance Minor */
            balance_minor: number;
            /** Currency */
            currency: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** CloseRequest */
        CloseRequest: {
            /** Reason Code */
            reason_code: string;
        };
        /** ConfirmationRequest */
        ConfirmationRequest: {
            corrected_fields?: components["schemas"]["Correction"] | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "CONFIRM" | "DISPUTE" | "CORRECT";
            /** Reason Code */
            reason_code?: string | null;
            /** Version */
            version: number;
        };
        /** Correction */
        Correction: {
            /** Amount */
            amount?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Outstanding */
            outstanding?: string | null;
        };
        /** CounterpartyView */
        CounterpartyView: {
            /** Identity */
            identity: string;
            /** Invoice Count */
            invoice_count: number;
            /** Member Id */
            member_id: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** CurrencyList */
        CurrencyList: {
            /** Items */
            items: components["schemas"]["CurrencyOut"][];
        };
        /** CurrencyOut */
        CurrencyOut: {
            /** Code */
            code: string;
            /** Exponent */
            exponent: number;
            /** Name */
            name: string;
        };
        /** Estimate */
        Estimate: {
            actual: components["schemas"]["Money"];
            baseline: components["schemas"]["Money"];
            /** Break Even Fee Share Bps */
            break_even_fee_share_bps: number | null;
            /** Currency */
            currency: string;
            fee: components["schemas"]["Money"];
            /** Fee Share Bps */
            fee_share_bps: number;
            gross_payable: components["schemas"]["Money"];
            gross_savings: components["schemas"]["Money"];
            net_payable: components["schemas"]["Money"];
            /** Run Id */
            run_id: string | null;
            savings: components["schemas"]["Money"];
            /**
             * Source
             * @enum {string}
             */
            source: "RUN" | "INPUT";
            /** Standard Rate Bps */
            standard_rate_bps: number;
        };
        /**
         * EstimateRequest
         * @description Break-even calculator (MC-FEE-03). Uses a run's figures, or amounts typed in.
         */
        EstimateRequest: {
            /** Fee Share Bps */
            fee_share_bps: number;
            /** Gross Payable Minor */
            gross_payable_minor?: number | null;
            /** Net Payable Minor */
            net_payable_minor?: number | null;
            /** Run Id */
            run_id?: string | null;
            /** Standard Rate Bps */
            standard_rate_bps: number;
        };
        /** ExpireApprovals */
        ExpireApprovals: {
            /** Run Id */
            run_id: string;
        };
        /** FundingFailure */
        FundingFailure: {
            /** Member Id */
            member_id: string;
            /**
             * Unable To Fund
             * @default true
             */
            unable_to_fund: boolean;
        };
        /** FundingState */
        FundingState: {
            /** Funding Blocked */
            funding_blocked: boolean;
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Name */
            name: string;
        };
        /** Generate */
        Generate: {
            /** Currencies */
            currencies?: string[];
            /**
             * Cycle Density
             * @default 50
             */
            cycle_density: number;
            /**
             * Invoices
             * @default 30
             */
            invoices: number;
            /**
             * Members
             * @default 6
             */
            members: number;
            /**
             * Seed
             * @default 1
             */
            seed: number;
        };
        /**
         * GraphEdge
         * @description Invoice edges point from payer to receiver (issuer); so do transfer edges.
         */
        GraphEdge: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /** Id */
            id: string;
            /**
             * Invoice Count
             * @default 0
             */
            invoice_count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "INVOICE" | "SETTLEMENT" | "FX_LEG";
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "MEMBER" | "SELF" | "COUNTERPARTY" | "MESH" | "FX" | "CARRY";
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldView */
        HoldView: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Member Name */
            member_name: string;
            /** Status */
            status: string;
        };
        /** InvoiceCreate */
        InvoiceCreate: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Due Date */
            due_date: string;
            /** Invoice Number */
            invoice_number: string;
            /** Issue Date */
            issue_date: string;
            /** Issuer Tax Id */
            issuer_tax_id: string;
            /**
             * Outstanding
             * @default
             */
            outstanding: string;
            /** Payer Tax Id */
            payer_tax_id: string;
        };
        /** InvoiceDetail */
        InvoiceDetail: {
            /** Amount Minor */
            amount_minor: number;
            /** Audit */
            audit: {
                [key: string]: unknown;
            }[];
            /** Confirmations */
            confirmations: {
                [key: string]: unknown;
            }[];
            /** Counterparty */
            counterparty: string;
            /** Counterparty Member Id */
            counterparty_member_id: string | null;
            /** Currency */
            currency: string;
            /** Current Version */
            current_version: number;
            /** Direction */
            direction: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Exclusions */
            exclusions: {
                [key: string]: unknown;
            }[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invoice Number */
            invoice_number: string;
            /**
             * Issue Date
             * Format: date
             */
            issue_date: string;
            /** Issuer Tax Id */
            issuer_tax_id: string;
            /** Needs Confirmation */
            needs_confirmation: boolean;
            /** Outcomes */
            outcomes: {
                [key: string]: unknown;
            }[];
            /** Outstanding Minor */
            outstanding_minor: number;
            /** Payer Tax Id */
            payer_tax_id: string;
            /** Status */
            status: string;
            /** Versions */
            versions: {
                [key: string]: unknown;
            }[];
        };
        /** InvoiceView */
        InvoiceView: {
            /** Amount Minor */
            amount_minor: number;
            /** Counterparty */
            counterparty: string;
            /** Counterparty Member Id */
            counterparty_member_id: string | null;
            /** Currency */
            currency: string;
            /** Current Version */
            current_version: number;
            /** Direction */
            direction: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invoice Number */
            invoice_number: string;
            /**
             * Issue Date
             * Format: date
             */
            issue_date: string;
            /** Issuer Tax Id */
            issuer_tax_id: string;
            /** Needs Confirmation */
            needs_confirmation: boolean;
            /** Outstanding Minor */
            outstanding_minor: number;
            /** Payer Tax Id */
            payer_tax_id: string;
            /** Status */
            status: string;
        };
        /** JobView */
        JobView: {
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error: string | null;
            /** Member Id */
            member_id: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Step */
            step: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KillRequest */
        KillRequest: {
            /** Enabled */
            enabled: boolean;
            /** Member Id */
            member_id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "GLOBAL" | "MEMBER";
        };
        /** KillView */
        KillView: {
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Member Id */
            member_id: string | null;
            /** Reason */
            reason: string | null;
            /** Scope */
            scope: string;
        };
        /** LedgerCheck */
        LedgerCheck: {
            /** Active Holds */
            active_holds: number;
            /** Breaks */
            breaks: components["schemas"]["ClearingBreak"][];
            /** Chain Ok */
            chain_ok: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Clearing Ok */
            clearing_ok: boolean;
            /** Entries */
            entries: number;
            /** First Break Seq */
            first_break_seq: number | null;
            /** Ok */
            ok: boolean;
            /** Unbalanced Entries */
            unbalanced_entries: number[];
        };
        /**
         * LedgerLine
         * @description One of the member's own ledger movements. The counterparty is always Mesh settlement.
         */
        LedgerLine: {
            /**
             * Account
             * @enum {string}
             */
            account: "BALANCE" | "HELD" | "CARRIED";
            amount: components["schemas"]["Money"];
            /**
             * Counterparty
             * @default Mesh settlement
             */
            counterparty: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Entry Kind */
            entry_kind: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            /** Demo Mode */
            demo_mode: boolean;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            member: components["schemas"]["MemberSummary"] | null;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MemberDetail */
        MemberDetail: {
            /** Balances */
            balances: components["schemas"]["BalanceOut"][];
            /** Legal Name */
            legal_name: string;
            maker_checker_threshold: components["schemas"]["Money"] | null;
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Name */
            name: string;
            payable_limit: components["schemas"]["Money"] | null;
            /** Risk Tier */
            risk_tier: string;
            /** Settlement Currency */
            settlement_currency: string;
            state: components["schemas"]["MemberState"];
        };
        /** MemberRow */
        MemberRow: {
            /** Funding Blocked */
            funding_blocked: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
        };
        /**
         * MemberSettlement
         * @description The member's own side of settlement (MC-PRV-02): no other member is ever named.
         */
        MemberSettlement: {
            amount: components["schemas"]["Money"];
            carried: components["schemas"]["Money"] | null;
            /**
             * Counterparty
             * @default Mesh settlement
             */
            counterparty: string;
            held: components["schemas"]["Money"] | null;
            /**
             * Instruction
             * @enum {string}
             */
            instruction: "DEBIT" | "CREDIT" | "NONE";
            /** Ledger */
            ledger: components["schemas"]["LedgerLine"][];
            /** Reference */
            reference: string;
            /** Settled By Netting */
            settled_by_netting: number;
            /** Settled By Transfer */
            settled_by_transfer: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "FUNDS_HELD" | "SETTLED" | "CANCELLED";
        };
        /**
         * MemberState
         * @enum {string}
         */
        MemberState: "INVITED" | "ONBOARDING" | "ACTIVE" | "RESTRICTED" | "SUSPENDED" | "OFFBOARDED";
        /** MemberSummary */
        MemberSummary: {
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /** Name */
            name: string;
            /** Settlement Currency */
            settlement_currency: string;
            state: components["schemas"]["MemberState"];
        };
        /** Money */
        Money: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
        };
        /** NetworkView */
        NetworkView: {
            /** Attempt */
            attempt: number | null;
            /** Gross Minor */
            gross_minor: {
                [key: string]: number;
            };
            /** Invoice Edges */
            invoice_edges: components["schemas"]["GraphEdge"][];
            /** Net Minor */
            net_minor: {
                [key: string]: number;
            };
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Run Id */
            run_id: string | null;
            /** Run Status */
            run_status: string | null;
            /** Runs */
            runs: components["schemas"]["RunChoice"][];
            /**
             * Source
             * @enum {string}
             */
            source: "RUN" | "WINDOW" | "MEMBER";
            /** Transfer Edges */
            transfer_edges: components["schemas"]["GraphEdge"][];
        };
        /** NotificationList */
        NotificationList: {
            /** Items */
            items: components["schemas"]["NotificationView"][];
            /** Unread Count */
            unread_count: number;
        };
        /** NotificationView */
        NotificationView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At */
            read_at: string | null;
            /** Type */
            type: string;
        };
        /** Page[AuditView] */
        Page_AuditView_: {
            /** Items */
            items: components["schemas"]["AuditView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[CaseView] */
        Page_CaseView_: {
            /** Items */
            items: components["schemas"]["CaseView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[CounterpartyView] */
        Page_CounterpartyView_: {
            /** Items */
            items: components["schemas"]["CounterpartyView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[InvoiceView] */
        Page_InvoiceView_: {
            /** Items */
            items: components["schemas"]["InvoiceView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[RunView] */
        Page_RunView_: {
            /** Items */
            items: components["schemas"]["RunView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Persona */
        Persona: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Member Name */
            member_name: string | null;
            role: components["schemas"]["Role"];
        };
        /** PersonaList */
        PersonaList: {
            /** Items */
            items: components["schemas"]["Persona"][];
            /** Password */
            password: string;
        };
        /** RateList */
        RateList: {
            /** Items */
            items: components["schemas"]["RateOut"][];
        };
        /** RateOut */
        RateOut: {
            /** Base */
            base: string;
            /** Quote */
            quote: string;
            /** Rate */
            rate: string;
            /** Source */
            source: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
        };
        /**
         * ReasonRequest
         * @description Every Wise staff action carries a reason code (MC-OPS-01).
         */
        ReasonRequest: {
            /** Reason Code */
            reason_code: string;
        };
        /** ResetResult */
        ResetResult: {
            /** Ok */
            ok: boolean;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "MEMBER_ADMIN" | "FINANCE_USER" | "APPROVER" | "WISE_OPS" | "WISE_COMPLIANCE";
        /** RunChoice */
        RunChoice: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** RunView */
        RunView: {
            /** Approvals */
            approvals?: {
                [key: string]: unknown;
            }[];
            /** Computations */
            computations?: {
                [key: string]: unknown;
            }[];
            /** Content Hash */
            content_hash?: string | null;
            /** Current Attempt */
            current_attempt: number;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Own Positions */
            own_positions?: {
                [key: string]: unknown;
            }[];
            settlement?: components["schemas"]["MemberSettlement"] | null;
            settlement_detail?: components["schemas"]["SettlementDetail"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Statement Id */
            statement_id?: string | null;
            /** Status */
            status: string;
            /** Status Reason */
            status_reason?: string | null;
            /** Timeline */
            timeline?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * SavingsItem
         * @description One run, in the member's settlement currency. `savings` is baseline minus actual.
         */
        SavingsItem: {
            actual: components["schemas"]["Money"];
            baseline: components["schemas"]["Money"];
            /** Currency */
            currency: string;
            fee: components["schemas"]["Money"];
            gross_payable: components["schemas"]["Money"];
            net_paid: components["schemas"]["Money"];
            net_received: components["schemas"]["Money"];
            /** Price Version */
            price_version: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            savings: components["schemas"]["Money"];
            /** Settled */
            settled: boolean;
            /** Settled At */
            settled_at: string | null;
            /** Status */
            status: string;
        };
        /** SavingsSummary */
        SavingsSummary: {
            /** Items */
            items: components["schemas"]["SavingsItem"][];
            /** Totals */
            totals: components["schemas"]["SavingsTotal"][];
        };
        /** SavingsTotal */
        SavingsTotal: {
            actual: components["schemas"]["Money"];
            baseline: components["schemas"]["Money"];
            /** Currency */
            currency: string;
            fee: components["schemas"]["Money"];
            gross_payable: components["schemas"]["Money"];
            net_paid: components["schemas"]["Money"];
            /** Runs */
            runs: number;
            savings: components["schemas"]["Money"];
        };
        /**
         * SettlementDetail
         * @description Wise staff view of a run's settlement: holds, jobs, transfers and clearing.
         */
        SettlementDetail: {
            /** Clearing */
            clearing: components["schemas"]["AccountBalance"][];
            /** Commit Entry Seq */
            commit_entry_seq: number | null;
            /** Holds */
            holds: components["schemas"]["HoldView"][];
            /** Jobs */
            jobs: components["schemas"]["JobView"][];
            /** Transfers */
            transfers: components["schemas"]["TransferView"][];
        };
        /** Simulate */
        Simulate: {
            /**
             * Confirm Pct
             * @default 100
             */
            confirm_pct: number;
            /**
             * Dispute Pct
             * @default 0
             */
            dispute_pct: number;
            /**
             * Seed
             * @default 1
             */
            seed: number;
        };
        /** StatementView */
        StatementView: {
            /** Approval Count */
            approval_count: number;
            /** Can Approve */
            can_approve: boolean;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /** Content Hash */
            content_hash: string;
            /** Current */
            current: boolean;
            /** Current Statement Id */
            current_statement_id: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Required Approvers */
            required_approvers: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Run Status */
            run_status: string;
        };
        /** TransferView */
        TransferView: {
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /** Kind */
            kind: string;
            /** Payer */
            payer: string;
            /** Receiver */
            receiver: string;
            /** Status */
            status: string;
        };
        /** UploadError */
        UploadError: {
            /** Field */
            field: string;
            /** Reason */
            reason: string;
            /** Row */
            row: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Errors */
            errors: components["schemas"]["UploadError"][];
            /** Items */
            items: components["schemas"]["InvoiceView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindowView */
        WindowView: {
            /** Eligible Count */
            eligible_count: number;
            /** Eligible Invoice Ids */
            eligible_invoice_ids: string[];
            /** Excluded Count */
            excluded_count: number;
            /** Exclusions */
            exclusions: {
                [key: string]: unknown;
            }[];
            /** Horizon Days */
            horizon_days: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_events_v1_admin_audit_events_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                subject_type?: string | null;
                subject_id?: string | null;
                /** @description Exact action or a prefix ending in '.' */
                action?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_v1_admin_cases_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CaseView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switches_v1_admin_kill_switches_put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ledger_check_v1_admin_ledger_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerCheck"];
                };
            };
        };
    };
    admin_network_v1_admin_network_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverview"];
                };
            };
        };
    };
    admin_run_v1_admin_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_v1_admin_runs__run_id__abort_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settle_v1_admin_runs__run_id__settle_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_v1_admin_windows_current_close_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inbox_v1_confirmations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvoiceView_"];
                };
            };
        };
    };
    counterparties_v1_counterparties_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CounterpartyView_"];
                };
            };
        };
    };
    list_currencies_v1_currencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyList"];
                };
            };
        };
    };
    expire_approvals_v1_demo_expire_approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpireApprovals"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funding_failure_v1_demo_funding_failure_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundingFailure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_v1_demo_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Generate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personas_v1_demo_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaList"];
                };
            };
        };
    };
    reset_v1_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_v1_demo_scenarios__name__post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_v1_demo_simulate_confirmations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Simulate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_v1_estimates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_v1_invoices_get: {
        parameters: {
            query?: {
                direction?: ("RECEIVABLE" | "PAYABLE") | null;
                status?: string[] | null;
                counterparty?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvoiceView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_v1_invoices_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_v1_invoices_template_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_v1_invoices_uploads_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_v1_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_v1_invoices__invoice_id__confirmations_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    get_my_member_v1_members_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetail"];
                };
            };
        };
    };
    my_network_v1_network_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkView"];
                };
            };
        };
    };
    notifications_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_v1_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rates_v1_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateList"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunView_"];
                };
            };
        };
    };
    run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    savings_v1_savings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsSummary"];
                };
            };
        };
    };
    statement_v1_statements__statement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_v1_statements__statement_id__approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_v1_windows_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindowView"];
                };
            };
        };
    };
}
