"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 12:32:50.023892
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("code", sa.CHAR(length=3), nullable=False),
        sa.Column("exponent", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.CheckConstraint("exponent BETWEEN 0 AND 4", name=op.f("ck_currencies_exponent_range")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_table(
        "legal_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("tax_id", sa.Text(), nullable=False),
        sa.Column("registration_no", sa.Text(), nullable=True),
        sa.Column("country", sa.CHAR(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entities")),
        sa.UniqueConstraint("tax_id", "country", name=op.f("uq_legal_entities_tax_id")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_processed_at"), "outbox_events", ["processed_at"], unique=False
    )
    op.create_table(
        "sanctions_list",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.CHAR(length=2), nullable=False),
        sa.Column("tax_id", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sanctions_list")),
    )
    op.create_table(
        "windows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=True),
        sa.Column("rules_version", sa.Text(), nullable=False),
        sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name=op.f("ck_windows_status_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_windows")),
    )
    op.create_index(
        "uq_windows_one_open",
        "windows",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("base", sa.CHAR(length=3), nullable=False),
        sa.Column("quote", sa.CHAR(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("base <> quote", name=op.f("ck_fx_rates_distinct_pair")),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rates_rate_positive")),
        sa.ForeignKeyConstraint(
            ["base"], ["currencies.code"], name=op.f("fk_fx_rates_base_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["quote"], ["currencies.code"], name=op.f("fk_fx_rates_quote_currencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rates")),
        sa.UniqueConstraint("base", "quote", "valid_from", name=op.f("uq_fx_rates_base")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("risk_tier", sa.Text(), nullable=False),
        sa.Column("settlement_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("payable_limit_minor", sa.BigInteger(), nullable=True),
        sa.Column("maker_checker_minor", sa.BigInteger(), nullable=True),
        sa.Column("agreement_version", sa.Text(), nullable=True),
        sa.Column("funding_blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "risk_tier IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f("ck_members_risk_tier_valid")
        ),
        sa.CheckConstraint(
            "state IN ('INVITED', 'ONBOARDING', 'ACTIVE', 'RESTRICTED', 'SUSPENDED', 'OFFBOARDED')",
            name=op.f("ck_members_state_valid"),
        ),
        sa.CheckConstraint(
            "maker_checker_minor IS NULL OR maker_checker_minor >= 0", name=op.f("ck_members_mc")
        ),
        sa.CheckConstraint(
            "payable_limit_minor IS NULL OR payable_limit_minor >= 0", name=op.f("ck_members_limit")
        ),
        sa.ForeignKeyConstraint(
            ["legal_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_members_legal_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["settlement_currency"],
            ["currencies.code"],
            name=op.f("fk_members_settlement_currency_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("legal_entity_id", name=op.f("uq_members_legal_entity_id")),
    )
    op.create_index(
        op.f("ix_members_legal_entity_id"), "members", ["legal_entity_id"], unique=False
    )
    op.create_table(
        "netting_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_attempt", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.Text(), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('FROZEN', 'SCREENED', 'COMPUTED', 'AWAITING_APPROVAL', 'APPROVED', 'PREPARED', 'RECOMPUTING', 'COMMITTED', 'FALLBACK_GROSS', 'ABORTED')",
            name=op.f("ck_netting_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["window_id"], ["windows.id"], name=op.f("fk_netting_runs_window_id_windows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_netting_runs")),
        sa.UniqueConstraint("window_id", name=op.f("uq_netting_runs_window_id")),
    )
    op.create_index(op.f("ix_netting_runs_window_id"), "netting_runs", ["window_id"], unique=False)
    op.create_table(
        "fx_locks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("base", sa.CHAR(length=3), nullable=False),
        sa.Column("quote", sa.CHAR(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base"], ["currencies.code"], name=op.f("fk_fx_locks_base_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_fx_locks_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["quote"], ["currencies.code"], name=op.f("fk_fx_locks_quote_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_fx_locks_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_locks")),
    )
    op.create_index(op.f("ix_fx_locks_member_id"), "fx_locks", ["member_id"], unique=False)
    op.create_index(op.f("ix_fx_locks_run_id"), "fx_locks", ["run_id"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("hash_prev", sa.Text(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('OPENING', 'HOLD', 'COMMIT', 'RELEASE')",
            name=op.f("ck_journal_entries_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_journal_entries_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_journal_entries_idempotency_key")),
        sa.UniqueConstraint("seq", name=op.f("uq_journal_entries_seq")),
    )
    op.create_index(op.f("ix_journal_entries_run_id"), "journal_entries", ["run_id"], unique=False)
    op.create_table(
        "ledger_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "type IN ('MEMBER_BALANCE', 'MEMBER_HOLD', 'CLEARING', 'FX_CONVERSION', 'FEE_REVENUE', 'SUSPENSE')",
            name=op.f("ck_ledger_accounts_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_ledger_accounts_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_ledger_accounts_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_ledger_accounts_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_accounts")),
        sa.UniqueConstraint(
            "type",
            "member_id",
            "run_id",
            "currency",
            name=op.f("uq_ledger_accounts_type"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_ledger_accounts_member_id"), "ledger_accounts", ["member_id"], unique=False
    )
    op.create_index(op.f("ix_ledger_accounts_run_id"), "ledger_accounts", ["run_id"], unique=False)
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("rule", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('ALLOW', 'EXCLUDE', 'HOLD_FOR_REVIEW', 'BLOCK')",
            name=op.f("ck_risk_decisions_decision_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_risk_decisions_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    op.create_index(op.f("ix_risk_decisions_run_id"), "risk_decisions", ["run_id"], unique=False)
    op.create_table(
        "run_computations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.Text(), nullable=False),
        sa.Column("excluded_members", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("algo_version", sa.Text(), nullable=False),
        sa.Column("seed", sa.Text(), nullable=False),
        sa.Column("result_hash", sa.Text(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt BETWEEN 1 AND 3", name=op.f("ck_run_computations_attempt_range")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_run_computations_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_computations")),
        sa.UniqueConstraint("run_id", "attempt", name=op.f("uq_run_computations_run_id")),
    )
    op.create_index(
        op.f("ix_run_computations_run_id"), "run_computations", ["run_id"], unique=False
    )
    op.create_table(
        "settlement_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('STARTED', 'DONE', 'FAILED')", name=op.f("ck_settlement_jobs_status_valid")
        ),
        sa.CheckConstraint(
            "step IN ('PREPARE', 'COMMIT', 'ABORT')", name=op.f("ck_settlement_jobs_step_valid")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_settlement_jobs_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_settlement_jobs_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_settlement_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_settlement_jobs_run_id"), "settlement_jobs", ["run_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role IN ('WISE_OPS', 'WISE_COMPLIANCE')) = (member_id IS NULL)",
            name=op.f("ck_users_staff_have_no_member"),
        ),
        sa.CheckConstraint(
            "role IN ('MEMBER_ADMIN', 'FINANCE_USER', 'APPROVER', 'WISE_OPS', 'WISE_COMPLIANCE')",
            name=op.f("ck_users_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_users_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_member_id"), "users", ["member_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("before_hash", sa.Text(), nullable=True),
        sa.Column("after_hash", sa.Text(), nullable=True),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_run_id"), "audit_events", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_subject_id"), "audit_events", ["subject_id"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_REVIEW', 'CLOSED')", name=op.f("ck_cases_status_valid")
        ),
        sa.CheckConstraint(
            "type IN ('SANCTIONS', 'RING', 'ENGINE_ALERT', 'FUNDING')",
            name=op.f("ck_cases_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_cases_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_cases_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_run_id"), "cases", ["run_id"], unique=False)
    op.create_table(
        "fee_charges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("baseline_minor", sa.BigInteger(), nullable=False),
        sa.Column("actual_minor", sa.BigInteger(), nullable=False),
        sa.Column("savings_minor", sa.BigInteger(), nullable=False),
        sa.Column("fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("price_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "baseline_minor >= 0 AND actual_minor >= 0 AND savings_minor >= 0 AND fee_minor >= 0",
            name=op.f("ck_fee_charges_non_negative"),
        ),
        sa.CheckConstraint(
            "fee_minor <= savings_minor", name=op.f("ck_fee_charges_fee_within_savings")
        ),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_fee_charges_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_fee_charges_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_fee_charges_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_charges")),
        sa.UniqueConstraint(
            "computation_id", "member_id", name=op.f("uq_fee_charges_computation_id")
        ),
    )
    op.create_index(
        op.f("ix_fee_charges_computation_id"), "fee_charges", ["computation_id"], unique=False
    )
    op.create_index(op.f("ix_fee_charges_member_id"), "fee_charges", ["member_id"], unique=False)
    op.create_table(
        "fx_legs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("from_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("from_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("to_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("to_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_fx_legs_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["from_currency"], ["currencies.code"], name=op.f("fk_fx_legs_from_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_fx_legs_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["to_currency"], ["currencies.code"], name=op.f("fk_fx_legs_to_currency_currencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_legs")),
    )
    op.create_index(op.f("ix_fx_legs_computation_id"), "fx_legs", ["computation_id"], unique=False)
    op.create_index(op.f("ix_fx_legs_member_id"), "fx_legs", ["member_id"], unique=False)
    op.create_table(
        "holds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("release_entry_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'CONSUMED', 'RELEASED')", name=op.f("ck_holds_status_valid")
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_holds_amount_positive")),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_holds_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_holds_journal_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_holds_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["release_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_holds_release_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_holds_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holds")),
        sa.UniqueConstraint("run_id", "member_id", "currency", name=op.f("uq_holds_run_id")),
    )
    op.create_index(op.f("ix_holds_member_id"), "holds", ["member_id"], unique=False)
    op.create_index(op.f("ix_holds_run_id"), "holds", ["run_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer_entity_id", sa.Uuid(), nullable=True),
        sa.Column("payer_entity_id", sa.Uuid(), nullable=True),
        sa.Column("issuer_member_id", sa.Uuid(), nullable=True),
        sa.Column("payer_member_id", sa.Uuid(), nullable=True),
        sa.Column("uploader_member_id", sa.Uuid(), nullable=False),
        sa.Column("counterparty_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("invoice_number", sa.Text(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("outstanding_minor", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('CSV', 'MANUAL', 'GENERATED', 'SCENARIO')",
            name=op.f("ck_invoices_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('IMPORTED', 'MATCHED', 'UNMATCHED', 'REJECTED_DATA', 'PENDING_CONFIRMATION', 'CONFIRMED', 'AMENDED', 'DISPUTED', 'LOCKED_IN_RUN', 'RELEASED', 'SETTLED_BY_NETTING', 'SETTLED_BY_TRANSFER', 'CANCELLED')",
            name=op.f("ck_invoices_status_valid"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_invoices_amount_positive")),
        sa.CheckConstraint("due_date >= issue_date", name=op.f("ck_invoices_dates")),
        sa.CheckConstraint(
            "issuer_member_id IS NULL OR payer_member_id IS NULL OR issuer_member_id <> payer_member_id",
            name=op.f("ck_invoices_distinct_parties"),
        ),
        sa.CheckConstraint(
            "outstanding_minor >= 0 AND outstanding_minor <= amount_minor",
            name=op.f("ck_invoices_outstanding"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_invoices_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_invoices_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["issuer_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_invoices_issuer_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["issuer_member_id"], ["members.id"], name=op.f("fk_invoices_issuer_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["payer_entity_id"],
            ["legal_entities.id"],
            name=op.f("fk_invoices_payer_entity_id_legal_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["payer_member_id"], ["members.id"], name=op.f("fk_invoices_payer_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["uploader_member_id"],
            ["members.id"],
            name=op.f("fk_invoices_uploader_member_id_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_invoices_fingerprint")),
    )
    op.create_index(
        op.f("ix_invoices_issuer_entity_id"), "invoices", ["issuer_entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_issuer_member_id"), "invoices", ["issuer_member_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_payer_entity_id"), "invoices", ["payer_entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_payer_member_id"), "invoices", ["payer_member_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_uploader_member_id"), "invoices", ["uploader_member_id"], unique=False
    )
    op.create_table(
        "kill_switches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope = 'GLOBAL') = (member_id IS NULL)", name=op.f("ck_kill_switches_scope_member")
        ),
        sa.CheckConstraint(
            "scope IN ('GLOBAL', 'MEMBER')", name=op.f("ck_kill_switches_scope_valid")
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["users.id"], name=op.f("fk_kill_switches_changed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_kill_switches_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switches")),
    )
    op.create_index(
        op.f("ix_kill_switches_member_id"), "kill_switches", ["member_id"], unique=False
    )
    op.create_index(
        "uq_kill_switches_global",
        "kill_switches",
        ["scope"],
        unique=True,
        postgresql_where=sa.text("scope = 'GLOBAL'"),
    )
    op.create_index(
        "uq_kill_switches_member",
        "kill_switches",
        ["member_id"],
        unique=True,
        postgresql_where=sa.text("scope = 'MEMBER'"),
    )
    op.create_table(
        "net_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("party_type", sa.Text(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("gross_in_minor", sa.BigInteger(), nullable=False),
        sa.Column("gross_out_minor", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(party_type = 'MEMBER') = (member_id IS NOT NULL)", name=op.f("ck_net_positions_party")
        ),
        sa.CheckConstraint(
            "party_type IN ('MEMBER', 'FX', 'CARRY')",
            name=op.f("ck_net_positions_party_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_net_positions_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_net_positions_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_net_positions_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_net_positions")),
    )
    op.create_index(
        op.f("ix_net_positions_computation_id"), "net_positions", ["computation_id"], unique=False
    )
    op.create_index(
        op.f("ix_net_positions_member_id"), "net_positions", ["member_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["outbox_events.id"], name=op.f("fk_notifications_event_id_outbox_events")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("event_id", "user_id", name=op.f("uq_notifications_event_id")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "planned_transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("payer_party", sa.Text(), nullable=False),
        sa.Column("payer_member_id", sa.Uuid(), nullable=True),
        sa.Column("receiver_party", sa.Text(), nullable=False),
        sa.Column("receiver_member_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('SETTLEMENT', 'FX_LEG')", name=op.f("ck_planned_transfers_kind_valid")
        ),
        sa.CheckConstraint(
            "payer_party IN ('MEMBER', 'FX', 'CARRY')",
            name=op.f("ck_planned_transfers_payer_party_valid"),
        ),
        sa.CheckConstraint(
            "receiver_party IN ('MEMBER', 'FX', 'CARRY')",
            name=op.f("ck_planned_transfers_receiver_party_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PLANNED', 'SETTLED', 'CANCELLED')",
            name=op.f("ck_planned_transfers_status_valid"),
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_planned_transfers_amount_positive")),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_planned_transfers_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_planned_transfers_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["payer_member_id"],
            ["members.id"],
            name=op.f("fk_planned_transfers_payer_member_id_members"),
        ),
        sa.ForeignKeyConstraint(
            ["receiver_member_id"],
            ["members.id"],
            name=op.f("fk_planned_transfers_receiver_member_id_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planned_transfers")),
    )
    op.create_index(
        op.f("ix_planned_transfers_computation_id"),
        "planned_transfers",
        ["computation_id"],
        unique=False,
    )
    op.create_table(
        "postings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount_minor <> 0", name=op.f("ck_postings_non_zero")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ledger_accounts.id"],
            name=op.f("fk_postings_account_id_ledger_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_postings_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_postings_journal_entry_id_journal_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_postings")),
    )
    op.create_index(op.f("ix_postings_account_id"), "postings", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_postings_journal_entry_id"), "postings", ["journal_entry_id"], unique=False
    )
    op.create_table(
        "rate_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=True),
        sa.Column("base", sa.CHAR(length=3), nullable=False),
        sa.Column("quote", sa.CHAR(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rate > 0", name=op.f("ck_rate_snapshots_rate_positive")),
        sa.ForeignKeyConstraint(
            ["base"], ["currencies.code"], name=op.f("fk_rate_snapshots_base_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_rate_snapshots_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["quote"], ["currencies.code"], name=op.f("fk_rate_snapshots_quote_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_rate_snapshots_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_snapshots")),
    )
    op.create_index(
        op.f("ix_rate_snapshots_computation_id"), "rate_snapshots", ["computation_id"], unique=False
    )
    op.create_index(op.f("ix_rate_snapshots_run_id"), "rate_snapshots", ["run_id"], unique=False)
    op.create_table(
        "statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("required_approvers", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_statements_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_statements_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statements")),
        sa.UniqueConstraint(
            "computation_id", "member_id", name=op.f("uq_statements_computation_id")
        ),
    )
    op.create_index(
        op.f("ix_statements_computation_id"), "statements", ["computation_id"], unique=False
    )
    op.create_index(op.f("ix_statements_member_id"), "statements", ["member_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("approver_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('APPROVED', 'REJECTED')", name=op.f("ck_approvals_decision_valid")
        ),
        sa.CheckConstraint(
            "method IN ('USER', 'CARRIED_FORWARD')", name=op.f("ck_approvals_method_valid")
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"], ["users.id"], name=op.f("fk_approvals_approver_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["statements.id"], name=op.f("fk_approvals_statement_id_statements")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("statement_id", "approver_id", name=op.f("uq_approvals_statement_id")),
    )
    op.create_index(op.f("ix_approvals_statement_id"), "approvals", ["statement_id"], unique=False)
    op.create_table(
        "cancellations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("computation_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("cycle_no", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_cancellations_amount_positive")),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_cancellations_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_cancellations_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cancellations")),
    )
    op.create_index(
        op.f("ix_cancellations_computation_id"), "cancellations", ["computation_id"], unique=False
    )
    op.create_index(
        op.f("ix_cancellations_invoice_id"), "cancellations", ["invoice_id"], unique=False
    )
    op.create_table(
        "confirmations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("party_member_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('CONFIRMED', 'DISPUTED')", name=op.f("ck_confirmations_decision_valid")
        ),
        sa.CheckConstraint(
            "method IN ('USER', 'AUTO', 'SIMULATED')", name=op.f("ck_confirmations_method_valid")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_confirmations_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_confirmations_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["party_member_id"],
            ["members.id"],
            name=op.f("fk_confirmations_party_member_id_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confirmations")),
        sa.UniqueConstraint(
            "invoice_id", "version", "party_member_id", name=op.f("uq_confirmations_invoice_id")
        ),
    )
    op.create_index(
        op.f("ix_confirmations_invoice_id"), "confirmations", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_confirmations_party_member_id"), "confirmations", ["party_member_id"], unique=False
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_member_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("contact_email", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED', 'EXPIRED')", name=op.f("ck_invitations_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["from_member_id"], ["members.id"], name=op.f("fk_invitations_from_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_invitations_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index(
        op.f("ix_invitations_from_member_id"), "invitations", ["from_member_id"], unique=False
    )
    op.create_index(op.f("ix_invitations_invoice_id"), "invitations", ["invoice_id"], unique=False)
    op.create_table(
        "invoice_exclusions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("computation_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("excluded_member_id", sa.Uuid(), nullable=True),
        sa.Column("public_reason", sa.Text(), nullable=False),
        sa.Column("internal_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "internal_reason IN ('NOT_MATCHED', 'NOT_CONFIRMED', 'DISPUTED', 'MEMBER_NOT_ACTIVE', 'COUNTERPARTY_UNAVAILABLE', 'NO_RATE', 'OUTSIDE_HORIZON', 'KILL_SWITCH', 'AGREEMENT_PENDING', 'SANCTIONS_HIT', 'HOLD_FOR_REVIEW', 'LIMIT_EXCEEDED', 'WITHDRAWN', 'REJECTED_STATEMENT', 'APPROVAL_EXPIRED', 'FUNDING_FAILED', 'UNDER_REVIEW')",
            name=op.f("ck_invoice_exclusions_internal_reason_valid"),
        ),
        sa.CheckConstraint(
            "public_reason IN ('NOT_MATCHED', 'NOT_CONFIRMED', 'DISPUTED', 'MEMBER_NOT_ACTIVE', 'COUNTERPARTY_UNAVAILABLE', 'NO_RATE', 'OUTSIDE_HORIZON', 'KILL_SWITCH', 'AGREEMENT_PENDING', 'SANCTIONS_HIT', 'HOLD_FOR_REVIEW', 'LIMIT_EXCEEDED', 'WITHDRAWN', 'REJECTED_STATEMENT', 'APPROVAL_EXPIRED', 'FUNDING_FAILED', 'UNDER_REVIEW')",
            name=op.f("ck_invoice_exclusions_public_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["computation_id"],
            ["run_computations.id"],
            name=op.f("fk_invoice_exclusions_computation_id_run_computations"),
        ),
        sa.ForeignKeyConstraint(
            ["excluded_member_id"],
            ["members.id"],
            name=op.f("fk_invoice_exclusions_excluded_member_id_members"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_invoice_exclusions_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_invoice_exclusions_run_id_netting_runs")
        ),
        sa.ForeignKeyConstraint(
            ["window_id"], ["windows.id"], name=op.f("fk_invoice_exclusions_window_id_windows")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_exclusions")),
    )
    op.create_index(
        op.f("ix_invoice_exclusions_computation_id"),
        "invoice_exclusions",
        ["computation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_exclusions_invoice_id"), "invoice_exclusions", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_exclusions_run_id"), "invoice_exclusions", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_exclusions_window_id"), "invoice_exclusions", ["window_id"], unique=False
    )
    op.create_table(
        "invoice_outcomes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("outstanding_minor", sa.BigInteger(), nullable=False),
        sa.Column("cancelled_minor", sa.BigInteger(), nullable=False),
        sa.Column("residual_minor", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(outcome = 'SETTLED_BY_NETTING') = (residual_minor = 0)",
            name=op.f("ck_invoice_outcomes_outcome_matches"),
        ),
        sa.CheckConstraint(
            "outcome IN ('SETTLED_BY_NETTING', 'SETTLED_BY_TRANSFER')",
            name=op.f("ck_invoice_outcomes_outcome_valid"),
        ),
        sa.CheckConstraint(
            "cancelled_minor >= 0 AND residual_minor >= 0 AND cancelled_minor + residual_minor = outstanding_minor",
            name=op.f("ck_invoice_outcomes_g6_balance"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_invoice_outcomes_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_invoice_outcomes_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_outcomes")),
        sa.UniqueConstraint("invoice_id", "run_id", name=op.f("uq_invoice_outcomes_invoice_id")),
    )
    op.create_index(
        op.f("ix_invoice_outcomes_invoice_id"), "invoice_outcomes", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_outcomes_run_id"), "invoice_outcomes", ["run_id"], unique=False
    )
    op.create_table(
        "invoice_versions",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.Text(), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "change_type IN ('CREATED', 'CORRECTED')",
            name=op.f("ck_invoice_versions_change_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_invoice_versions_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_invoice_versions_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("invoice_id", "version", name=op.f("pk_invoice_versions")),
    )
    op.create_table(
        "run_invoices",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payer_member_id", sa.Uuid(), nullable=False),
        sa.Column("receiver_member_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("outstanding_minor", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "outstanding_minor > 0", name=op.f("ck_run_invoices_outstanding_positive")
        ),
        sa.ForeignKeyConstraint(
            ["currency"], ["currencies.code"], name=op.f("fk_run_invoices_currency_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_run_invoices_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["payer_member_id"],
            ["members.id"],
            name=op.f("fk_run_invoices_payer_member_id_members"),
        ),
        sa.ForeignKeyConstraint(
            ["receiver_member_id"],
            ["members.id"],
            name=op.f("fk_run_invoices_receiver_member_id_members"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_run_invoices_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "invoice_id", name=op.f("pk_run_invoices")),
    )
    op.create_table(
        "withdrawals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_withdrawals_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_withdrawals_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_withdrawals_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["netting_runs.id"], name=op.f("fk_withdrawals_run_id_netting_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_withdrawals")),
        sa.UniqueConstraint("run_id", "invoice_id", name=op.f("uq_withdrawals_run_id")),
    )
    op.create_index(op.f("ix_withdrawals_invoice_id"), "withdrawals", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_withdrawals_member_id"), "withdrawals", ["member_id"], unique=False)
    op.create_index(op.f("ix_withdrawals_run_id"), "withdrawals", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_withdrawals_run_id"), table_name="withdrawals")
    op.drop_index(op.f("ix_withdrawals_member_id"), table_name="withdrawals")
    op.drop_index(op.f("ix_withdrawals_invoice_id"), table_name="withdrawals")
    op.drop_table("withdrawals")
    op.drop_table("run_invoices")
    op.drop_table("invoice_versions")
    op.drop_index(op.f("ix_invoice_outcomes_run_id"), table_name="invoice_outcomes")
    op.drop_index(op.f("ix_invoice_outcomes_invoice_id"), table_name="invoice_outcomes")
    op.drop_table("invoice_outcomes")
    op.drop_index(op.f("ix_invoice_exclusions_window_id"), table_name="invoice_exclusions")
    op.drop_index(op.f("ix_invoice_exclusions_run_id"), table_name="invoice_exclusions")
    op.drop_index(op.f("ix_invoice_exclusions_invoice_id"), table_name="invoice_exclusions")
    op.drop_index(op.f("ix_invoice_exclusions_computation_id"), table_name="invoice_exclusions")
    op.drop_table("invoice_exclusions")
    op.drop_index(op.f("ix_invitations_invoice_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_from_member_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_confirmations_party_member_id"), table_name="confirmations")
    op.drop_index(op.f("ix_confirmations_invoice_id"), table_name="confirmations")
    op.drop_table("confirmations")
    op.drop_index(op.f("ix_cancellations_invoice_id"), table_name="cancellations")
    op.drop_index(op.f("ix_cancellations_computation_id"), table_name="cancellations")
    op.drop_table("cancellations")
    op.drop_index(op.f("ix_approvals_statement_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_statements_member_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_computation_id"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(op.f("ix_rate_snapshots_run_id"), table_name="rate_snapshots")
    op.drop_index(op.f("ix_rate_snapshots_computation_id"), table_name="rate_snapshots")
    op.drop_table("rate_snapshots")
    op.drop_index(op.f("ix_postings_journal_entry_id"), table_name="postings")
    op.drop_index(op.f("ix_postings_account_id"), table_name="postings")
    op.drop_table("postings")
    op.drop_index(op.f("ix_planned_transfers_computation_id"), table_name="planned_transfers")
    op.drop_table("planned_transfers")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_net_positions_member_id"), table_name="net_positions")
    op.drop_index(op.f("ix_net_positions_computation_id"), table_name="net_positions")
    op.drop_table("net_positions")
    op.drop_index(
        "uq_kill_switches_member",
        table_name="kill_switches",
        postgresql_where=sa.text("scope = 'MEMBER'"),
    )
    op.drop_index(
        "uq_kill_switches_global",
        table_name="kill_switches",
        postgresql_where=sa.text("scope = 'GLOBAL'"),
    )
    op.drop_index(op.f("ix_kill_switches_member_id"), table_name="kill_switches")
    op.drop_table("kill_switches")
    op.drop_index(op.f("ix_invoices_uploader_member_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_payer_member_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_payer_entity_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_issuer_member_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_issuer_entity_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_holds_run_id"), table_name="holds")
    op.drop_index(op.f("ix_holds_member_id"), table_name="holds")
    op.drop_table("holds")
    op.drop_index(op.f("ix_fx_legs_member_id"), table_name="fx_legs")
    op.drop_index(op.f("ix_fx_legs_computation_id"), table_name="fx_legs")
    op.drop_table("fx_legs")
    op.drop_index(op.f("ix_fee_charges_member_id"), table_name="fee_charges")
    op.drop_index(op.f("ix_fee_charges_computation_id"), table_name="fee_charges")
    op.drop_table("fee_charges")
    op.drop_index(op.f("ix_cases_run_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_events_subject_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_run_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_member_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_settlement_jobs_run_id"), table_name="settlement_jobs")
    op.drop_table("settlement_jobs")
    op.drop_index(op.f("ix_run_computations_run_id"), table_name="run_computations")
    op.drop_table("run_computations")
    op.drop_index(op.f("ix_risk_decisions_run_id"), table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_ledger_accounts_run_id"), table_name="ledger_accounts")
    op.drop_index(op.f("ix_ledger_accounts_member_id"), table_name="ledger_accounts")
    op.drop_table("ledger_accounts")
    op.drop_index(op.f("ix_journal_entries_run_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_fx_locks_run_id"), table_name="fx_locks")
    op.drop_index(op.f("ix_fx_locks_member_id"), table_name="fx_locks")
    op.drop_table("fx_locks")
    op.drop_index(op.f("ix_netting_runs_window_id"), table_name="netting_runs")
    op.drop_table("netting_runs")
    op.drop_index(op.f("ix_members_legal_entity_id"), table_name="members")
    op.drop_table("members")
    op.drop_table("fx_rates")
    op.drop_index(
        "uq_windows_one_open", table_name="windows", postgresql_where=sa.text("status = 'OPEN'")
    )
    op.drop_table("windows")
    op.drop_table("sanctions_list")
    op.drop_index(op.f("ix_outbox_events_processed_at"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("legal_entities")
    op.drop_table("idempotency_keys")
    op.drop_table("currencies")
    # ### end Alembic commands ###
